//! Parser for the `.PKGINFO` key/value file written by `makepkg`.

use std::collections::BTreeMap;

#[derive(Debug, thiserror::Error)]
pub enum PkgInfoError {
    #[error("line {line}: expected `key = value`")]
    Malformed { line: usize },
    #[error("missing required key `{0}`")]
    MissingKey(&'static str),
}

/// Raw `.PKGINFO` contents. Keys may repeat (`depend`, `provides`, `backup`, ...),
/// so values are collected in order.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct PkgInfo {
    pub entries: BTreeMap<String, Vec<String>>,
}

impl PkgInfo {
    pub fn parse(text: &str) -> Result<Self, PkgInfoError> {
        let mut entries: BTreeMap<String, Vec<String>> = BTreeMap::new();
        for (idx, raw) in text.lines().enumerate() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (key, value) = line
                .split_once('=')
                .ok_or(PkgInfoError::Malformed { line: idx + 1 })?;
            entries
                .entry(key.trim().to_owned())
                .or_default()
                .push(value.trim().to_owned());
        }
        Ok(Self { entries })
    }

    pub fn first(&self, key: &str) -> Option<&str> {
        self.entries
            .get(key)
            .and_then(|v| v.first())
            .map(String::as_str)
    }

    pub fn all(&self, key: &str) -> &[String] {
        self.entries.get(key).map_or(&[], Vec::as_slice)
    }

    pub fn required(&self, key: &'static str) -> Result<&str, PkgInfoError> {
        self.first(key).ok_or(PkgInfoError::MissingKey(key))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "\
# Generated by makepkg 7.0.0
pkgname = flea
pkgbase = flea
pkgver = 1.2.0-1
pkgdesc = Tiny example
url = https://example.org
builddate = 1700000000
packager = Omarchy <build@omarchy.org>
size = 12345
arch = x86_64
license = MIT
depend = glibc
depend = openssl>=3
provides = libflea.so=1-64
backup = etc/flea.conf
";

    #[test]
    fn parses_repeated_keys() {
        let info = PkgInfo::parse(SAMPLE).unwrap();
        assert_eq!(info.first("pkgname"), Some("flea"));
        assert_eq!(info.all("depend"), ["glibc", "openssl>=3"]);
        assert_eq!(info.all("provides"), ["libflea.so=1-64"]);
        assert_eq!(info.required("pkgver").unwrap(), "1.2.0-1");
        assert!(matches!(
            info.required("nope"),
            Err(PkgInfoError::MissingKey("nope"))
        ));
    }

    #[test]
    fn rejects_malformed_lines() {
        assert!(matches!(
            PkgInfo::parse("pkgname flea"),
            Err(PkgInfoError::Malformed { line: 1 })
        ));
    }
}
