[package]
name = "pkg-store"
description = "Local ACID state store (redb), staging area and transactional filesystem engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
pkg-manifest = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
redb = "2"
tar = "0.4"
zstd = "0.13"
rustix = { version = "1", features = ["process"] }

[dev-dependencies]
pkg-extract = { workspace = true }
tempfile = "3"

[lints]
workspace = true
